name: Update blog post list


on:
  schedule:
    # Runs once every five days
    - cron: '0 0 */5 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: gautamkrishnar/blog-post-workflow@1.4.2
        with:
          comment_tag_name: "PERSONAL-BLOG-POST-LIST"
          feed_list: "https://kolappan.dev/feed.xml"
